 modbus_controller:
   - id: R4DCB08_01
     address: 1
     modbus_id: modbus1
     update_interval: 5s
     offline_skip_updates: 60

    
select:
  - platform: modbus_controller
    modbus_controller_id: R4DCB08_01
    name: "R4DCB08 Baud"
    address: 0x00FF
    value_type: U_WORD
    optionsmap:
      "1200": 0
      "2400": 1
      "4800": 2
      "9600": 3
      "19200": 4
      "Reset (9600)": 5

      
number:
  - platform: modbus_controller
    modbus_controller_id: R4DCB08_01
    name: "R4DCB08 Address"
    address: 254 #0x00FE
    value_type: U_WORD
    min_value: 1
    max_value: 247


sensor:
  - platform: modbus_controller
    modbus_controller_id: R4DCB08_01
    id: R4DCB08_01_1
    name: 'Temp Sensor CH1'
    address: 0x0000
    register_type: holding
    value_type: S_WORD 
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    filters:
    - multiply: 0.1
    - throttle_average: 15s
    - filter_out: -32768
    - filter_out: -3276.8
  - platform: modbus_controller
    modbus_controller_id: R4DCB08_01
    id: R4DCB08_01_2
    name: 'Temp Sensor CH2'
    address: 0x0001
    register_type: holding
    value_type: S_WORD 
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    filters:
    - multiply: 0.1 
    - throttle_average: 15s
    - filter_out: -32768
    - filter_out: -3276.8
  - platform: modbus_controller
    modbus_controller_id: R4DCB08_01
    id: R4DCB08_01_3
    name: 'Temp Sensor CH3'
    address: 0x0002
    register_type: holding
    value_type: S_WORD 
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    filters:
    - multiply: 0.1 
    - throttle_average: 15s
    - filter_out: -32768
    - filter_out: -3276.8
  - platform: modbus_controller
    modbus_controller_id: R4DCB08_01
    id: R4DCB08_01_4
    name: 'Temp Sensor CH4'
    address: 0x0003
    register_type: holding
    value_type: S_WORD 
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    filters:
    - multiply: 0.1 
    - throttle_average: 15s
    - filter_out: -32768
    - filter_out: -3276.8
  - platform: modbus_controller
    modbus_controller_id: R4DCB08_01
    id: R4DCB08_01_5
    name: 'Temp Sensor CH5'
    address: 0x0004
    register_type: holding
    value_type: S_WORD 
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    filters:
    - multiply: 0.1 
    - throttle_average: 15s
    - filter_out: -32768
    - filter_out: -3276.8
  - platform: modbus_controller
    modbus_controller_id: R4DCB08_01
    id: R4DCB08_01_6
    name: 'Temp Sensor CH6'
    address: 0x0005
    register_type: holding
    value_type: S_WORD 
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    filters:
    - multiply: 0.1 
    - throttle_average: 15s
    - filter_out: -32768
    - filter_out: -3276.8
  - platform: modbus_controller
    modbus_controller_id: R4DCB08_01
    id: R4DCB08_01_7
    name: 'Temp Sensor CH7'
    address: 0x0006
    register_type: holding
    value_type: S_WORD 
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    filters:
    - multiply: 0.1 
    - throttle_average: 15s
    - filter_out: -32768
    - filter_out: -3276.8
  - platform: modbus_controller
    modbus_controller_id: R4DCB08_01
    id: R4DCB08_01_8
    name: 'Temp Sensor CH8'
    address: 0x0007
    register_type: holding
    value_type: S_WORD 
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    filters:
    - multiply: 0.1 
    - throttle_average: 15s
    - filter_out: -32768
    - filter_out: -3276.8
